require("config.options")
require("config.keymaps")
require("config.local")
require("config.lazy")
require("lsp.clang")
-- require("plugins.colorschemes")
-- require("plugins.telescope")
-- require("plugins.comment")
-- require("plugins.marks")
-- require("plugins.lualine")
-- require("plugins.tmux-navigator")
